### PR TITLE
Fix RAML

### PR DESCRIPTION
**Pull request by ex-nerd**
This branch tracks my fixes to the RAML language parsing, including updates/extensions to the original.

It will look a lot cleaner after applying my other pull request at #6, though I've tried to keep individual commits fairly atomic so they could be applied individual if necessary.

### CODE REVIEW

**Comment by ex-nerd** [comment]
Just wondering if anyone is watching this repo.  There are PRs open since January.

**Comment by FedeAmdan** [comment]
Hi @ex-nerd, I'm really sorry for the delay, this contribution is awesome! 
I noticed that in Sublime 2  the schemas are not painted after applying this version of the tmLanguage. I will try to dig into the problem to see if changing the regex fixes the problem.
schema

**Comment by ex-nerd** [comment]
Interesting.  When I started using ST, I went straight for 3, since it's been relatively stable for several years.  But differences between the two could definitely explain why most of the formatting rules defined don't seem to work at all in 3.

**Comment by ex-nerd** [comment]
Sorry for leaving your reply sitting in my inbox for too long.  Anyway, I finally took some time to get ST2 up and running and see if I could reproduce the issue.  I found a glitch with one of the `end` tag regex patterns, and it is now properly identifying as `markup.raw.description.raml.schema` in both ST2 and ST3.

**Comment by FedeAmdan** [comment]
Hi @ex-nerd, I can still see the issue in the schemas (in ST2 and ST3). I could fix it by changing the line:
<string>markup.raw.description.raml.schema</string> (line 188) to <string>string.quoted.single.yaml</string> (which is the yellow colour in the yaml highlighter, using the default theme). I will accept your pull request and change that line. BTW Thanks for signing the contribution agreement.

**Comment by ex-nerd** [comment]
Interesting.  I guess markup.raw.description.* isn't highlighted by the default theme (I'm using Neon, with some of my own additions via https://github.com/MattDMo/Neon-color-scheme/pull/19).  It seemed a better choice than "string" since in RAML the values are likely to be more large.  But better that it gets colorized, thanks.

**Pull request merged**
